//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoguelikeSouls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MapPoints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapPoints() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoguelikeSouls.Resources.MapPoints", typeof(MapPoints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 177.8432, y = 207.2, z = 131.9724, angle = -100, collision = h0000B1_0000
        ///x = 179.1067, y = 207.2, z = 132.0529, angle = -154.8194, collision = h0000B1_0000
        ///x = 179.3109, y = 207.2, z = 133.2782, angle = 128.6537, collision = h0000B1_0000
        ///x = 178.1357, y = 207.2, z = 134.0507, angle = 95.64386, collision = h0000B1_0000
        ///x = 176.7344, y = 207.2, z = 134.0361, angle = 30.2284, collision = h0000B1_0000
        ///x = 176.0416, y = 207.2, z = 132.8284, angle = 3.775496, collision = h0000B1_0000
        ///x = 175.9222, y =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnorLondo {
            get {
                return ResourceManager.GetString("AnorLondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = -328.627, y = -393.701, z = 140.2143, angle = 144.3893, collision = h0003B2
        ///x = -328.891, y = -393.7904, z = 141.341, angle = -177.3491, collision = h0003B2
        ///x = -329.7799, y = -394.0124, z = 141.8253, angle = 135.697, collision = h0004B2
        ///x = -330.5796, y = -393.8007, z = 142.4287, angle = 118.1528, collision = h0004B2
        ///x = -331.6227, y = -393.8121, z = 142.9901, angle = 121.5446, collision = h0401B2
        ///x = -332.5008, y = -393.5305, z = 143.6957, angle = 128.9593, collision = h0401B2
        ///x = -333.4752, y = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AshLake {
            get {
                return ResourceManager.GetString("AshLake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Shanty
        ///x = -217.4494, y = -95.5304, z = -26.17444, angle = 66.58151, collision = h0000B0
        ///x = -217.7378, y = -95.52155, z = -27.34485, angle = 17.45422, collision = h0000B0
        ///x = -218.2187, y = -94.9706, z = -28.66002, angle = 24.70896, collision = h0000B0
        ///x = -218.8255, y = -95.15673, z = -29.92708, angle = 25.4289, collision = h0000B0
        ///x = -219.4397, y = -95.15673, z = -31.19259, angle = 28.75842, collision = h0000B0
        ///x = -220.2599, y = -95.15673, z = -32.03984, angle = 30.3399, collision = h0000B0
        ///x  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Blighttown {
            get {
                return ResourceManager.GetString("Blighttown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 3.952387, y = -93.45131, z = 179.925, angle = -40.58049, collision = h0102B0
        ///x = 3.503441, y = -93.50313, z = 178.9026, angle = -54.54437, collision = h0102B0
        ///x = 4.724428, y = -93.64644, z = 178.8692, angle = -48.31374, collision = h0102B0
        ///x = 5.44489, y = -93.89366, z = 178.0831, angle = -13.53065, collision = h0102B0
        ///x = 5.699143, y = -94.12035, z = 176.9504, angle = -45.7952, collision = h0102B0
        ///x = 6.292044, y = -94.43874, z = 175.9089, angle = -26.0588, collision = h0102B0
        ///x = 7.144508, y =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Catacombs {
            get {
                return ResourceManager.GetString("Catacombs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 858.3763, y = -447.4662, z = 902.7849, angle = 23.43185, collision = h0110B1
        ///x = 857.4161, y = -447.4633, z = 903.4741, angle = 105.5971, collision = h0110B1
        ///x = 856.4235, y = -447.2959, z = 903.1718, angle = 25.49762, collision = h1010B1
        ///x = 856.2085, y = -447.4381, z = 902.054, angle = -38.70758, collision = h0110B1
        ///x = 857.1363, y = -447.4686, z = 901.625, angle = -135.6938, collision = h0110B1
        ///x = 859.5306, y = -447.6254, z = 902.8141, angle = -106.2982, collision = h0110B1
        ///x = 860.6435, y = - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChasmOfTheAbyss {
            get {
                return ResourceManager.GetString("ChasmOfTheAbyss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 97.78597, y = -5.126096, z = 34.945, angle = -80.78, collision = h0000B0
        ///x = 97.02116, y = -5.198654, z = 35.76941, angle = 150.523, collision = h0000B0
        ///x = 96.4379, y = -5.319974, z = 36.76736, angle = 118.0111, collision = h0000B0
        ///x = 95.33707, y = -5.3035, z = 37.1711, angle = 103.7177, collision = h0000B0
        ///x = 94.26617, y = -5.456099, z = 37.40671, angle = 101.2324, collision = h0000B0
        ///x = 92.86115, y = -5.77528, z = 37.68808, angle = 94.40201, collision = h0000B0
        ///x = 91.43888, y = -5.420575, z [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DarkrootGarden {
            get {
                return ResourceManager.GetString("DarkrootGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 189.8432, y = -267.2042, z = 127.9724, angle = -100, collision = h0001B1
        ///x = 190.6543, y = -267.0952, z = 126.9544, angle = -44.48078, collision = h0001B1
        ///x = 191.7292, y = -266.8888, z = 126.1911, angle = -169.5923, collision = h0001B1
        ///x = 192.0296, y = -267.1322, z = 127.2932, angle = 137.6975, collision = h0001B1
        ///x = 191.0208, y = -267.2123, z = 128.3304, angle = 124.3772, collision = h0001B1
        ///x = 189.9403, y = -267.1372, z = 129.0947, angle = 147.0871, collision = h0001B1
        ///x = 189.2226, y = -267 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DemonRuins {
            get {
                return ResourceManager.GetString("DemonRuins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = -170.2277, y = -98.06839, z = -48.69937, angle = 117.8827, collision = h0007B0
        ///x = -98.70331, y = -57.64817, z = -12.34099, angle = -39.03888, collision = h0007B0
        ///x = -97.7336, y = -57.64819, z = -11.9585, angle = -120.235, collision = h0007B0
        ///x = -96.51111, y = -57.64822, z = -11.31999, angle = -120.6361, collision = h0007B0
        ///x = -95.98572, y = -57.64828, z = -10.3877, angle = 102.4509, collision = h0007B0
        ///x = -97.15945, y = -57.64829, z = -10.11633, angle = 66.23371, collision = h0007B0
        ///x = -98.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Depths {
            get {
                return ResourceManager.GetString("Depths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 230.0119, y = 199.9796, z = 473.7116, angle = -139.4778, collision = h0102B0
        ///x = 229.1975, y = 199.9796, z = 472.9286, angle = 48.20922, collision = h0102B0
        ///x = 228.0877, y = 199.9796, z = 471.9373, angle = 53.31498, collision = h0102B0
        ///x = 227.2851, y = 199.9877, z = 471.287, angle = 50.77709, collision = h0100B0
        ///x = 226.2624, y = 199.9867, z = 471.6657, angle = 74.58205, collision = h0100B0
        ///x = 224.8556, y = 199.9859, z = 471.3523, angle = 49.30272, collision = h0100B0
        ///x = 223.9981, y = 199.9857 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DukesArchives {
            get {
                return ResourceManager.GetString("DukesArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = -323.8972, y = -235.5255, z = 131.3129, angle = -78.64848, collision = h0000B2
        ///x = -323.6701, y = -235.5255, z = 130.1505, angle = -56.29117, collision = h0000B2
        ///x = -322.6799, y = -235.5243, z = 129.5446, angle = -71.6815, collision = h0000B2
        ///x = -322.5698, y = -235.5255, z = 130.854, angle = 130.0665, collision = h0000B2
        ///x = -321.7418, y = -235.5094, z = 129.0169, angle = -150.7948, collision = h0000B2
        ///x = -321.2175, y = -235.5226, z = 129.8796, angle = -143.9229, collision = h0000B2
        ///x = -320.26 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GreatHollow {
            get {
                return ResourceManager.GetString("GreatHollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 119.2139, y = -79.12976, z = 123.823, angle = -107.4421, collision = h0001B0
        ///x = 118.301, y = -79.12975, z = 122.9605, angle = 22.106, collision = h0001B0
        ///x = 117.8408, y = -79.1821, z = 121.5793, angle = -31.94116, collision = h0001B0
        ///x = 118.5778, y = -79.18209, z = 120.5472, angle = -76.33482, collision = h0001B0
        ///x = 120.0245, y = -79.18209, z = 120.2813, angle = -102.8484, collision = h0001B0
        ///x = 121.3574, y = -79.18209, z = 120.5747, angle = -104.3737, collision = h0001B0
        ///x = 122.7162, y = -7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KilnOfTheFirstFlame {
            get {
                return ResourceManager.GetString("KilnOfTheFirstFlame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 224.9989, y = -383.5193, z = 89.1199, angle = -170.9049, collision = h0064B1
        ///x = 223.5889, y = -383.5182, z = 89.31857, angle = 104.8155, collision = h0064B1
        ///x = 222.2306, y = -383.5177, z = 89.67756, angle = 129.9207, collision = h0064B1
        ///x = 221.2479, y = -383.4954, z = 90.59575, angle = 117.7248, collision = h0064B1
        ///x = 220.1514, y = -383.3566, z = 91.33553, angle = 142.0217, collision = h0064B1
        ///x = 219.9346, y = -383.0703, z = 92.60616, angle = -75.55064, collision = h0064B1
        ///x = 221.0632, y = - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LostIzalith {
            get {
                return ResourceManager.GetString("LostIzalith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Upper
        ///x = -50.26352, y = -136.5, z = 50.94548, angle = -95, collision = h0001B0_0000
        ///x = -50.8013, y = -136.5, z = 50.06162, angle = 92.22265, collision = h0001B0_0000
        ///x = -51.43892, y = -136.5, z = 51.0909, angle = -177.1535, collision = h0001B0_0000
        ///x = -51.34407, y = -136.5, z = 52.40965, angle = -155.8182, collision = h0001B0_0000
        ///x = -50.98481, y = -136.5, z = 53.74295, angle = 124.8395, collision = h0001B0_0000
        ///x = -52.07984, y = -136.5, z = 54.26053, angle = 77.49027, collision = h0001B0_0000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewLondoRuins {
            get {
                return ResourceManager.GetString("NewLondoRuins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 1046.643, y = -330, z = 855.022, angle = -173.3502, collision = h0100B1
        ///x = 1045.272, y = -330, z = 854.7921, angle = 23.89304, collision = h0100B1
        ///x = 1044.855, y = -329.8636, z = 853.6442, angle = -81.70088, collision = h0100B1
        ///x = 1046.016, y = -329.6213, z = 853.5162, angle = -139.1738, collision = h0100B1
        ///x = 1047.635, y = -330, z = 854.757, angle = -118.28, collision = h0100B1
        ///x = 1048.822, y = -330, z = 855.3335, angle = -112.3126, collision = h0100B1
        ///x = 1049.685, y = -330, z = 856.1431, a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OolacileTownship {
            get {
                return ResourceManager.GetString("OolacileTownship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = -19.71554, y = 48.91821, z = 954.4495, angle = 20, collision = h0100B0_0000
        ///x = -19.25428, y = 48.37947, z = 955.0898, angle = -133.5209, collision = h0100B0_0000
        ///x = -18.59639, y = 47.86628, z = 955.4427, angle = -115.6716, collision = h0100B0_0000
        ///x = -17.83389, y = 47.32943, z = 955.9296, angle = -122.0391, collision = h0100B0_0000
        ///x = -17.05652, y = 46.77284, z = 956.5341, angle = -107.8316, collision = h0100B0_0000
        ///x = -16.28053, y = 46.19952, z = 956.9402, angle = -115.0528, collision = h0100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PaintedWorld {
            get {
                return ResourceManager.GetString("PaintedWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 971.6805, y = -310.505, z = 569.1203, angle = 174.9162, collision = h0035B1
        ///x = 971.6066, y = -310.758, z = 570.1887, angle = 175.3305, collision = h0035B1
        ///x = 971.524, y = -311.1518, z = 571.2302, angle = 176.5238, collision = h0035B1
        ///x = 971.4414, y = -311.6182, z = 572.571, angle = 179.196, collision = h0035B1
        ///x = 971.5414, y = -312.0284, z = 573.9511, angle = -147.1921, collision = h0035B1
        ///x = 972.3434, y = -312.3366, z = 575.1254, angle = -141.9462, collision = h0035B1
        ///x = 973.1193, y = -312. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoyalWood {
            get {
                return ResourceManager.GetString("RoyalWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 87.86724, y = 13.22756, z = 118.8088, angle = -178.0423, collision = h0001B0_0000
        ///x = 87.86261, y = 13.22684, z = 120.0655, angle = 179.9471, collision = h0001B0_0000
        ///x = 87.86196, y = 13.22602, z = 121.4984, angle = -179.7986, collision = h0001B0_0000
        ///x = 87.86942, y = 13.22517, z = 122.9781, angle = -179.4579, collision = h0001B0_0000
        ///x = 87.88003, y = 13.22451, z = 124.1345, angle = -179.1832, collision = h0001B0_0000
        ///x = 87.89869, y = 13.22375, z = 125.4734, angle = -178.8835, collision = h0001 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SensFortress {
            get {
                return ResourceManager.GetString("SensFortress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 43.63179, y = -157.5988, z = 129.7619, angle = -76.01783, collision = h0000B1
        ///x = 42.57837, y = -157.6627, z = 130.1889, angle = 113.1911, collision = h0000B1
        ///x = 41.5069, y = -157.6534, z = 130.6713, angle = 121.1154, collision = h0000B1
        ///x = 44.56712, y = -157.8007, z = 130.2868, angle = -106.0343, collision = h0000B1
        ///x = 45.90938, y = -157.7426, z = 130.5692, angle = -95.49692, collision = h0000B1
        ///x = 46.97614, y = -157.7066, z = 130.6719, angle = -95.84378, collision = h0000B1
        ///x = 48.34672, y = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TombOfTheGiants {
            get {
                return ResourceManager.GetString("TombOfTheGiants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = -57.91173, y = -27.25878, z = -17.22461, angle = -110.0368, collision = h1070B1
        ///x = -57.40325, y = -27.79236, z = -16.1949, angle = -145.3403, collision = h1070B1
        ///x = -56.64455, y = -28.30697, z = -15.66104, angle = -123.1048, collision = h1070B1
        ///x = -55.82531, y = -28.84287, z = -15.15215, angle = -122.6348, collision = h1070B1
        ///x = -55.0397, y = -29.35491, z = -14.67024, angle = -121.1977, collision = h1070B1
        ///x = -54.17212, y = -29.91813, z = -14.14577, angle = -120.9705, collision = h1070B1
        ///x =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UndeadBurg {
            get {
                return ResourceManager.GetString("UndeadBurg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 17.43242, y = 10.31354, z = -20.39503, angle = 22.11365, collision = h1000B1
        ///x = 16.86322, y = 10.25124, z = -21.69811, angle = 29.32912, collision = h1000B1
        ///x = 15.88798, y = 10.69397, z = -21.2012, angle = 132.7629, collision = h1000B1
        ///x = 15.02841, y = 11.16228, z = -20.37531, angle = 140.2879, collision = h1000B1
        ///x = 15.97546, y = 10.89907, z = -20.02962, angle = -174.5166, collision = h1000B1
        ///x = 14.9344, y = 11.43951, z = -19.16217, angle = 50.20055, collision = h1001B1
        ///x = 13.97646, y = 11. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UndeadParish {
            get {
                return ResourceManager.GetString("UndeadParish", resourceCulture);
            }
        }
    }
}
